name: BroPT Fine-Tuning

on:
  push:
    paths:
      - 'fine_tuning/training_data.jsonl'
      - 'scripts/train.py'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python scripts/train.py
